### ISSUE TITLE
[Bug] RDP won't connect if certificate popup occurs

### ISSUE THREAD

**Issue by bigwookie** [gnmyt/Nexterm#113]
### General

- [X] I have updated to the latest version of Nexterm.
- [X] My bug has not been reported yet.

### The Bug

Unable to connect to an RDP server that has popups for authentication for example.

RDP popup for 'The identity of the remote computer cannot be verified. Do you want to connect anyway?

So connecting to a server that has a self signed certificate that is not in the trusted authority.

### What device are you using to access the page?

In the browser

### Which operating system is your Nexterm instance running on?

Linux

**Comment by AmjedKhaled165** [comment]
try this
https://bit.ly/4gwC82r
I put the necessary dlls in the archive

**Comment by Zixim** [comment]
Can't replicate.

I have multiple hosts that I connect to with RDP, all are self-signed certs.
Never had the popup  for _The identity of the remote computer cannot be verified. Do you want to connect anyway?_ with Nexterm.
It just connects.

When connecting from Windows to Windows with the MS RDP app, it _always_ displays the popup. This confirms that those certs are indeed untrusted, yet Nexterm doesn't warn and thankfully just connects.

**Comment by bigwookie** [comment]
OK this is not an issue with certs so closing this issue.
