### ISSUE TITLE
[Feature] SFTP support

### ISSUE THREAD

**Issue by gnmyt** [gnmyt/Nexterm#14]
### General

- [X] My feature does not exist in the latest version of Nexterm.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

Add support for downloading, viewing, editing and deleting files all from the same web interface using a right-click > Connect to SFTP

**Comment by cryptedx** [comment]
This would be a killer feature! :-D

**Comment by dalso0418** [comment]
I'm really looking forward to it :)

**Comment by xd003** [comment]
> Add support for downloading, viewing, editing and deleting files all from the same web interface using a right-click > Connect to SFTP

Or even better, can just display the all the files like mobaxterm does on the left side by default

**Comment by xd003** [comment]
@gnmyt 
Appreciate a lot for taking this one up. Just for info, in the current implementation, is it possible to enable SFTP by default and display files on the left hand side like mobaxterm does ? It just feels lot more accessible and easy
