### ISSUE TITLE
[Bug] Creating the first user account on a new instance with a single-character first name fails with an unclear error message

### ISSUE THREAD

**Issue by cid214** [gnmyt/Nexterm#23]
### General

- [X] I have updated to the latest version of Nexterm.
- [X] My bug has not been reported yet.

### The Bug

When you're creating the first account on a new instance, if you use a single-character first name, the error will tell you that your username or password is invalid when you click to create the account. (Might also apply to last name, but I didn't test that as putting in my full first name immediately cleared the issue and created the account.)

This is a little confusing, as the actual fault doesn't lie in either the username or password, and should perhaps have a more clear error message.

### What device are you using to access the page?

In the browser

### Which operating system is your Nexterm instance running on?

Linux

**Comment by gnmyt** [comment]
Thanks for reporting this. The next update will contain a proper sign-up error message
