### ISSUE TITLE
[Bug] Adding SSH server without password for private key fails

### ISSUE THREAD

**Issue by tecnicx15** [gnmyt/Nexterm#24]
### General

- [X] I have updated to the latest version of Nexterm.
- [X] My bug has not been reported yet.

### The Bug

When adding an ssh connection with keyfile instead of password, it asks for both the private key file and a password to unlock said file, it would be nice to allow adding private keys that are not secured by password.

This is a mandatory requirement as checked via browser developers tools, in the UI there is no clear error message it just keeps the form in place without doing anything.

### What device are you using to access the page?

In the browser

### Which operating system is your Nexterm instance running on?

Windows

**Comment by cid214** [comment]
I also noticed this, and it appears adding anything as the password/passphrase is enough to get the server added, and doesn't seem to prevent the key from working normally.

**Comment by gnmyt** [comment]
I completely agree with you. The bug will be fixed in the next update
