### ISSUE TITLE
[Bug] Screen display is truncated by leftside bar

### ISSUE THREAD

**Issue by bedelaitre** [gnmyt/Nexterm#35]
### General

- [X] I have updated to the latest version of Nexterm.
- [X] My bug has not been reported yet.

### The Bug

Using NextTerm in docker on a Synology NAS.
I have added two servers: one for RDP, one for VNC

The connexion is OK on both servers but the screen is truncated. Left and right parts are missing.

![With VNC client](https://github.com/user-attachments/assets/3200f339-49df-421f-a1be-cf0ac6c6de5b)
![Within Nexterm](https://github.com/user-attachments/assets/5ee6b2ec-cc49-433d-94ac-416292f697cd)

There must be an option to scroll screen or to resize it.

### What device are you using to access the page?

In the browser

### Which operating system is your Nexterm instance running on?

Linux

**Comment by gnmyt** [comment]
Thanks for reporting this. The problem should be fixed with the new version `v1.0.2-OPEN-PREVIEW`. If the problem still occurs in the new version, feel free to re-open this issue :)
