### ISSUE TITLE
[Feature] Reorder list of server

### ISSUE THREAD

**Issue by bedelaitre** [gnmyt/Nexterm#37]
### General

- [X] My feature does not exist in the latest version of Nexterm.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

I've created many server configurations. But I can't find how to reorder them. I haven't found any sort or reorder option

So, it might be useful to be able to:
   - Sort the list of folders
   - Manually reorder the list of folders
   - Sort the list of servers in a folder
   - Manually Reorder the list of servers in a folder
   - Change the folder for a server

**Comment by samumatic** [comment]
Possible duplicate of #25?

**Comment by gnmyt** [comment]
Sounds good! This will be implemented in the next release.

**Comment by binuengoor** [comment]
@gnmyt  when will this be released? I don't see this option in docker container
