### ISSUE TITLE
[Bug] can not connect with a VNC 

### ISSUE THREAD

**Issue by MSandro** [gnmyt/Nexterm#41]
### General

- [X] I have updated to the latest version of Nexterm.
- [X] My bug has not been reported yet.

### The Bug

I can not connect with my VNC Server.
```
guacd[8]: INFO:	Guacamole proxy daemon (guacd) version 1.6.0 started
guacd[8]: INFO:	Listening on host 0.0.0.0, port 4822
Successfully connected to the database file
Server listening on port 6989
Authorized connection to server vnc with identity Auto-generated identity
Error in Guacamole WebSocket: Error: connect ECONNREFUSED ::1:58391
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 58391
}
```

I am using Nexterm on a ARM64 Server.

### What device are you using to access the page?

In the browser

### Which operating system is your Nexterm instance running on?

Linux

**Comment by MSandro** [comment]
now I've tried RDP and VNC on a X86 CPU.
it does not work. SSH works well.

Just as feedback by the way: I love this idea, and the implementation of the web interface so far. If it works, it's sure to be great.

**Comment by gnmyt** [comment]
Thanks! This might be related to #3 so it should be fixed with the new PR I made. If it does not get fixed within the next version, feel free to re-open this issue. :)
