### ISSUE TITLE
[Bug] Error on 1.0.1

### ISSUE THREAD

**Issue by neroita** [gnmyt/Nexterm#56]
### General

- [X] I have updated to the latest version of Nexterm.
- [X] My bug has not been reported yet.

### The Bug

Latest version 1.0.1 don't start , it log a error:
Error: Could not find a free port for Guacamole

### What device are you using to access the page?

In the browser

### Which operating system is your Nexterm instance running on?

Linux

**Comment by gnmyt** [comment]
I've deployed a hotfix to the `development` tag of the docker image. Can you try running the container on this version to see if this fixes the issue?

```bash
docker run -d -p 6989:6989 --name nexterm --restart always -v nexterm:/app/data germannewsmaker/nexterm:development@sha256:0123004e71ea88b090ef67e460719c71dd161bffe60085e5d7d7256cae1da478
```

**Comment by neroita** [comment]
This work perfectly.

**Comment by neroita** [comment]
Will be a 1.0.2 version with the fix applyed ?

**Comment by gnmyt** [comment]
Yes, the 1.0.2 will contain this fix. I'll try to implement 1-2 more features and release the new version.
