### ISSUE TITLE
Don't dictate my password policy.

### ISSUE THREAD

**Issue by stayupthetree** [gnmyt/Nexterm#63]
### General

- [X] My feature does not exist in the latest version of Nexterm.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

![image](https://github.com/user-attachments/assets/3a272ed0-6e37-4dc7-9c4e-2a62cb3d6e68)

Security is up to me.

**Comment by gnmyt** [comment]
Fair enough, I'll open up a PR to change this behavior.
