### ISSUE TITLE
[Bug] Can't connect to VM's on Proxmox

### ISSUE THREAD

**Issue by heliohenriques** [gnmyt/Nexterm#76]
### General

- [X] I have updated to the latest version of Nexterm.
- [X] My bug has not been reported yet.

### The Bug

Let me start for congrats the amazing work done so far.
The Bug:
I made the integration with my Proxmox, and everything looks fine, less that I can't connect via SSH to my VM's. Screen keeps black and no connection.
 I'm able to connect to Lxc and Proxmox VE shell without issues.

### What device are you using to access the page?

In the browser

### Which operating system is your Nexterm instance running on?

Linux

**Comment by dnburgess** [comment]
Can confirm the same. Am able to start/stop a VM, but not connect to the shell.

**Comment by dazbeattie** [comment]
Firstly, what a great project. So clean and refreshing. 
I concur with David and others. Linux and Windows VMs is a blank screen, no connection. LXC connect fine.

**Comment by gnmyt** [comment]
Thanks for reporting this. Apparently, the problem was that `guacd` was running on version `1.6.0` instead of `1.5.5`, the latest stable version. I'll create a PR to fix this issue.
